@testpythonaspng.Server_HostAddress = https://localhost:7298

GET {{testpythonaspng.Server_HostAddress}}/weatherforecast/
Accept: application/json
###

GET {{testpythonaspng.Server_HostAddress}}/api/analysis

###

POST {{testpythonaspng.Server_HostAddress}}/api/analysis {}

###

POST {{testpythonaspng.Server_HostAddress}}/api/upload "AAA"

###
